/**
 * Solstice & Sage Restaurant - Curated Culinary Menu Data
 * High-definition imagery, detailed dietary markers, and sommelier pairings.
 */

const MENU_DATA = [
  // --- CHEF'S SIGNATURE SPECIALS ---
  {
    id: "dish-1",
    name: "Pan-Seared Chilean Sea Bass",
    category: "specials",
    categoryLabel: "Chef's Special",
    price: 48,
    rating: 4.9,
    reviewsCount: 184,
    prepTime: "25 mins",
    calories: "520 kcal",
    spiciness: 1,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80",
    description: "Sustainably caught sea bass served over a velvety saffron emulsion, heirloom asparagus spears, and finished with citrus herb oil.",
    ingredients: ["Chilean Sea Bass", "Spanish Saffron", "Heirloom Asparagus", "Meyer Lemon Emulsion", "Fennel Pollen", "Extra Virgin Olive Oil"],
    allergens: ["Fish", "Dairy"],
    dietary: ["gluten-free", "chef-recommended"],
    pairing: "Domaine Leflaive Puligny-Montrachet 2021",
    isChefSpecial: true,
    isPopular: true
  },
  {
    id: "dish-2",
    name: "Truffle-Glazed A5 Wagyu Ribeye",
    category: "specials",
    categoryLabel: "Chef's Special",
    price: 76,
    rating: 5.0,
    reviewsCount: 220,
    prepTime: "30 mins",
    calories: "780 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    description: "Miyazaki A5 Wagyu seared to medium-rare perfection, accented with winter black truffle demi-glace, confit garlic, and smoked potato mousseline.",
    ingredients: ["A5 Miyazaki Wagyu", "Périgord Black Truffle", "Smoked Yukon Gold Potatoes", "Shallot Confit", "Bone Marrow Demi-glace"],
    allergens: ["Dairy"],
    dietary: ["gluten-free", "chef-recommended"],
    pairing: "Château Margaux Premier Grand Cru 2018",
    isChefSpecial: true,
    isPopular: true
  },
  {
    id: "dish-3",
    name: "Handmade Morel & Ricotta Tortelloni",
    category: "specials",
    categoryLabel: "Chef's Special",
    price: 38,
    rating: 4.8,
    reviewsCount: 142,
    prepTime: "20 mins",
    calories: "590 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
    description: "Delicate pasta pouches filled with house-whipped lemon ricotta and wild Oregon morels, bathed in brown butter sage and aged Parmigiano Reggiano.",
    ingredients: ["Semolina Egg Pasta", "Wild Morel Mushrooms", "Artisanal Buffalo Ricotta", "Cultured Brown Butter", "Crispy Sage", "24-Month Parmigiano"],
    allergens: ["Wheat/Gluten", "Dairy", "Eggs"],
    dietary: ["vegetarian", "chef-recommended"],
    pairing: "Barolo Vietti Castiglione 2019",
    isChefSpecial: true,
    isPopular: false
  },
  {
    id: "dish-4",
    name: "Deconstructed Dark Chocolate Dome",
    category: "specials",
    categoryLabel: "Chef's Special",
    price: 24,
    rating: 4.9,
    reviewsCount: 310,
    prepTime: "15 mins",
    calories: "450 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=800&q=80",
    description: "72% Valrhona single-origin dark chocolate dome filled with raspberry coulis and hazelnut praline, melted tableside with warm spiced caramel.",
    ingredients: ["Valrhona Dark Chocolate", "Piedmont Hazelnut Praline", "Wild Raspberry Coulis", "Madagascar Bourbon Vanilla Gelato", "24k Gold Flakes"],
    allergens: ["Dairy", "Tree Nuts", "Soy"],
    dietary: ["vegetarian", "chef-recommended"],
    pairing: "Taylor Fladgate 20-Year Tawny Port",
    isChefSpecial: true,
    isPopular: true
  },

  // --- STARTERS & CRUDO ---
  {
    id: "dish-5",
    name: "Hamachi Crudo with Yuzu Ponzu",
    category: "starters",
    categoryLabel: "Starters & Crudo",
    price: 26,
    rating: 4.8,
    reviewsCount: 98,
    prepTime: "12 mins",
    calories: "280 kcal",
    spiciness: 1,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
    description: "Thinly sliced Pacific yellowtail adorned with white truffle droplets, crisp watermelon radish, serrano pepper slice, and aged yuzu-soy vinaigrette.",
    ingredients: ["Pacific Yellowtail", "Yuzu Citrus", "Shiso Leaves", "Watermelon Radish", "Serrano Pepper", "Sesame Essence"],
    allergens: ["Fish", "Soy"],
    dietary: ["gluten-free"],
    pairing: "Dassai 23 Junmai Daiginjo Sake",
    isChefSpecial: false,
    isPopular: true
  },
  {
    id: "dish-6",
    name: "Crispy Duck Confit Croquettes",
    category: "starters",
    categoryLabel: "Starters & Crudo",
    price: 22,
    rating: 4.7,
    reviewsCount: 86,
    prepTime: "15 mins",
    calories: "420 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    description: "Golden panko crust filled with slow-cooked shredded duck leg, thyme-infused béchamel, accompanied by cherry-port reduction and microgreens.",
    ingredients: ["Duck Confit", "Panko Breadcrumbs", "Port Wine Glaze", "Morello Cherries", "Fresh Thyme"],
    allergens: ["Wheat/Gluten", "Dairy", "Eggs"],
    dietary: [],
    pairing: "Pinot Noir Domaine Drouhin Oregon 2021",
    isChefSpecial: false,
    isPopular: false
  },
  {
    id: "dish-7",
    name: "Heirloom Burrata & Roasted Fig Tartine",
    category: "starters",
    categoryLabel: "Starters & Crudo",
    price: 23,
    rating: 4.9,
    reviewsCount: 164,
    prepTime: "10 mins",
    calories: "380 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985b?auto=format&fit=crop&w=800&q=80",
    description: "Creamy artisanal pugliese burrata, caramelized black mission figs, wild clover honey, crushed pistachios, and balsamic pearls on grilled levain.",
    ingredients: ["Pugliese Burrata", "Mission Figs", "Artisanal Sourdough", "Bronte Pistachios", "Modena Aged Balsamic", "Micro Basil"],
    allergens: ["Dairy", "Wheat/Gluten", "Tree Nuts"],
    dietary: ["vegetarian"],
    pairing: "Prosecco Superiore Conegliano Valdobbiadene DOCG",
    isChefSpecial: false,
    isPopular: true
  },
  {
    id: "dish-8",
    name: "Wild Forest Mushroom Cappuccino",
    category: "starters",
    categoryLabel: "Starters & Crudo",
    price: 19,
    rating: 4.6,
    reviewsCount: 75,
    prepTime: "10 mins",
    calories: "240 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
    description: "Silky velouté of porcini, chanterelles, and cremini mushrooms capped with white truffle foam and served with brioche herb soldiers.",
    ingredients: ["Porcini Mushrooms", "Chanterelles", "Shallots", "Truffle Milk Foam", "French Butter Brioche"],
    allergens: ["Dairy", "Wheat/Gluten"],
    dietary: ["vegetarian"],
    pairing: "Chardonnay Kistler Les Noisetiers 2020",
    isChefSpecial: false,
    isPopular: false
  },

  // --- SIGNATURE MAINS ---
  {
    id: "dish-9",
    name: "Slow-Braised Prime Short Rib",
    category: "mains",
    categoryLabel: "Signature Mains",
    price: 46,
    rating: 4.9,
    reviewsCount: 204,
    prepTime: "25 mins",
    calories: "740 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    description: "Braised for 48 hours in Cabernet Sauvignon, served alongside parsnip-vanilla puree, glazed baby heirloom carrots, and bone marrow reduction.",
    ingredients: ["USDA Prime Beef Short Rib", "Cabernet Sauvignon", "Parsnip Silk", "Glazed Baby Carrots", "Crisp Leeks"],
    allergens: ["Dairy"],
    dietary: ["gluten-free"],
    pairing: "Silver Oak Alexander Valley Cabernet 2018",
    isChefSpecial: false,
    isPopular: true
  },
  {
    id: "dish-10",
    name: "Pan-Roasted Ora King Salmon",
    category: "mains",
    categoryLabel: "Signature Mains",
    price: 42,
    rating: 4.8,
    reviewsCount: 153,
    prepTime: "20 mins",
    calories: "610 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80",
    description: "Crispy-skinned New Zealand King Salmon over wild black forbidden rice, sauteed baby bok choy, and a lemongrass ginger beurre blanc.",
    ingredients: ["Ora King Salmon", "Forbidden Black Rice", "Baby Bok Choy", "Lemongrass Beurre Blanc", "Finger Lime"],
    allergens: ["Fish", "Dairy"],
    dietary: ["gluten-free"],
    pairing: "Cloudy Bay Sauvignon Blanc 2022",
    isChefSpecial: false,
    isPopular: true
  },
  {
    id: "dish-11",
    name: "Roasted Kabocha Squash & Saffron Risotto",
    category: "mains",
    categoryLabel: "Signature Mains",
    price: 34,
    rating: 4.7,
    reviewsCount: 112,
    prepTime: "20 mins",
    calories: "510 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=800&q=80",
    description: "Acquerello carnaroli rice simmered in vegetable consommé, sweet roasted Japanese pumpkin, crispy sage, pomegranate jewels, and pepitas.",
    ingredients: ["Acquerello Rice", "Kabocha Squash", "Vegetable Broth", "Pomegranate Seeds", "Crisp Sage", "Toasted Pepitas"],
    allergens: [],
    dietary: ["vegan", "gluten-free", "vegetarian"],
    pairing: "Vermentino di Sardegna La Cala 2021",
    isChefSpecial: false,
    isPopular: false
  },
  {
    id: "dish-12",
    name: "Herb-Crusted Rack of Colorado Lamb",
    category: "mains",
    categoryLabel: "Signature Mains",
    price: 52,
    rating: 4.9,
    reviewsCount: 178,
    prepTime: "28 mins",
    calories: "690 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1514944298352-78d120a17409?auto=format&fit=crop&w=800&q=80",
    description: "Dijon and rosemary-crusted tender lamb cutlets, served with smoked polenta, confit pearl onions, English pea coulis, and mint lamb jus.",
    ingredients: ["Colorado Lamb Rack", "Dijon Mustard", "Rosemary Panko", "Stone-ground Polenta", "Pearl Onions", "English Peas"],
    allergens: ["Wheat/Gluten", "Dairy"],
    dietary: [],
    pairing: "Châteauneuf-du-Pape Clos des Papes 2019",
    isChefSpecial: false,
    isPopular: false
  },

  // --- DESSERTS ---
  {
    id: "dish-13",
    name: "Tahitian Vanilla Mille-Feuille",
    category: "desserts",
    categoryLabel: "Artisanal Desserts",
    price: 18,
    rating: 4.8,
    reviewsCount: 130,
    prepTime: "12 mins",
    calories: "410 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    description: "Caramelized puff pastry wafers layered with light Tahitian vanilla bean diplomat cream, salted butter caramel drizzle, and candied pecans.",
    ingredients: ["Caramelized Feuilletage", "Tahitian Vanilla Beans", "Diplomat Cream", "Salted Butter Caramel", "Spiced Pecans"],
    allergens: ["Wheat/Gluten", "Dairy", "Eggs", "Tree Nuts"],
    dietary: ["vegetarian"],
    pairing: "Château d'Yquem Sauternes 2016",
    isChefSpecial: false,
    isPopular: false
  },
  {
    id: "dish-14",
    name: "Matcha & White Peach Panna Cotta",
    category: "desserts",
    categoryLabel: "Artisanal Desserts",
    price: 17,
    rating: 4.7,
    reviewsCount: 89,
    prepTime: "10 mins",
    calories: "320 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80",
    description: "Velvety Uji ceremonial grade matcha cream, infused white peach gelee, ginger snap crumble, and edible viola blossoms.",
    ingredients: ["Ceremonial Uji Matcha", "White Peach Purée", "Coconut & Dairy Cream", "Crystallized Ginger", "Edible Flowers"],
    allergens: ["Dairy"],
    dietary: ["gluten-free", "vegetarian"],
    pairing: "Moscato d'Asti Vietti Cascinetta 2022",
    isChefSpecial: false,
    isPopular: false
  },
  {
    id: "dish-15",
    name: "Meyer Lemon Meringue Sphere",
    category: "desserts",
    categoryLabel: "Artisanal Desserts",
    price: 19,
    rating: 4.9,
    reviewsCount: 145,
    prepTime: "12 mins",
    calories: "340 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    description: "Crispy Italian torched meringue crust concealing tangy lemon curd, basil mint granita, and shortbread crumb foundation.",
    ingredients: ["Meyer Lemon Curd", "Torched Italian Meringue", "Fresh Basil Granita", "Butter Shortbread"],
    allergens: ["Wheat/Gluten", "Dairy", "Eggs"],
    dietary: ["vegetarian"],
    pairing: "Limoncello di Sorrento Riserva",
    isChefSpecial: false,
    isPopular: true
  },

  // --- BEVERAGES & COCKTAILS ---
  {
    id: "dish-16",
    name: "The Solstice Golden Smoke",
    category: "beverages",
    categoryLabel: "Craft Cocktails & Wine",
    price: 21,
    rating: 5.0,
    reviewsCount: 240,
    prepTime: "6 mins",
    calories: "190 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80",
    description: "Small-batch Woodford Reserve bourbon, smoked rosemary syrup, charred orange peel, Angostura bitters, served under a cloche with Applewood smoke.",
    ingredients: ["Woodford Reserve Bourbon", "Applewood Smoke", "Smoked Rosemary Syrup", "Charred Orange Bitters", "Clear Hand-Cut Ice Block"],
    allergens: [],
    dietary: ["vegan", "gluten-free"],
    pairing: "Artisanal Charcuterie Board",
    isChefSpecial: true,
    isPopular: true
  },
  {
    id: "dish-17",
    name: "Lavender Mist Botanical Fizz",
    category: "beverages",
    categoryLabel: "Craft Cocktails & Wine",
    price: 18,
    rating: 4.8,
    reviewsCount: 167,
    prepTime: "5 mins",
    calories: "160 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=800&q=80",
    description: "Empress 1908 Indigo Gin, wild lavender flower reduction, clarified lemon juice, elderflower liqueur, topped with Brut sparkling champagne.",
    ingredients: ["Empress Indigo Gin", "Organic Provence Lavender", "Clarified Lemon", "St-Germain Elderflower", "French Brut Champagne"],
    allergens: [],
    dietary: ["vegan", "gluten-free"],
    pairing: "Hamachi Crudo",
    isChefSpecial: false,
    isPopular: true
  },
  {
    id: "dish-18",
    name: "Hibiscus Lychee Zero-Proof Elixir",
    category: "beverages",
    categoryLabel: "Craft Cocktails & Wine",
    price: 14,
    rating: 4.8,
    reviewsCount: 102,
    prepTime: "5 mins",
    calories: "110 kcal",
    spiciness: 0,
    image: "https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=800&q=80",
    description: "House-steeped organic hibiscus blossom tea, chilled lychee nectar, cold-pressed lime juice, sparkling mountain mineral water, and mint bouquet.",
    ingredients: ["Organic Hibiscus Blossom", "Sweet Lychee Nectar", "Key Lime Juice", "Sparkling Spring Water", "Fresh Mint"],
    allergens: [],
    dietary: ["vegan", "gluten-free", "alcohol-free"],
    pairing: "Any Appetizer or Main",
    isChefSpecial: false,
    isPopular: false
  }
];

// Helper functions for menu querying
window.SolsticeMenuData = {
  getAll: () => MENU_DATA,
  getById: (id) => MENU_DATA.find(item => item.id === id),
  getSpecials: () => MENU_DATA.filter(item => item.isChefSpecial),
  getByCategory: (category) => {
    if (!category || category === "all") return MENU_DATA;
    return MENU_DATA.filter(item => item.category === category);
  },
  getCategories: () => [
    { id: "all", name: "Full Menu", icon: "🍽️" },
    { id: "specials", name: "Chef's Specials", icon: "⭐" },
    { id: "starters", name: "Starters & Crudo", icon: "🥗" },
    { id: "mains", name: "Signature Mains", icon: "🥩" },
    { id: "desserts", name: "Artisanal Desserts", icon: "🍮" },
    { id: "beverages", name: "Craft Cocktails & Wine", icon: "🍸" }
  ]
};
